homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('extra/', views.extra, name='extra'),
    # dilanjutkan ...
]

stori1/urls.py
from django.urls import path
from . import views

app_name = 'stori1'

urlpatterns = [
    path('stori1', views.home, name='home'),
]

stori5/urls.py
from django.urls import path
from . import views

app_name = 'stori5'

urlpatterns = [
    path('daftar_matkul/', views.matkul, name='matkul'),
    path('detail_matkul/<int:index>/', views.detail_matkul, name='detail_matkul'),
    path('tambah/', views.tambah_matkul, name='tambah_matkul'),
]

stori6/urls.py
from django.urls import path
from . import views

app_name = 'stori6'

urlpatterns = [
    path('daftar_event/', views.event, name='event'),
    path('registrasi/<int:index>/', views.registrasi, name='registrasi'),
    path('tambah_event/', views.tambah_event, name='tambah_event'),
]

storyMirsa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stori1.urls')),
    path('', include('homepage.urls')),
    path('', include('stori5.urls')),
    path('', include('stori6.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

stori1/models.py
from django.db import models

# Create your models here.

stori5/models.py
from django.db import models

# Create your models here.

class Matkul(models.Model):
    subject = models.CharField(max_length=50)
    dosen = models.CharField(max_length=120)
    sks = models.IntegerField()
    deskripsi = models.TextField(blank=True)
    semester = models.CharField(max_length=120, help_text="2020/2021 ganjil")
    kelas = models.CharField(max_length=120, help_text="2204")

    def __str__(self):
        return self.subject

stori6/models.py
from django.db import models

# Create your models here.
class Event(models.Model) :
    name = models.CharField(max_length=128)
    def __str__(self) :
        return self.name

class Participant(models.Model) :
    name = models.CharField(max_length=128)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    def __str__(self) :
        return str(self.event) + " - " + self.name

stori6/forms.py
from django.forms import ModelForm
from .models import *

class EventForm(ModelForm):
	required_css_class = 'required'
	class Meta:
		model = Event
		fields = '__all__'

class ParticipantForm(ModelForm):
	class Meta:
		model = Participant
		fields = ['name']

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'stori3.html')

def extra(request):
    return render(request, 'extra.html')

stori1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'stori1.html')

stori5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .form import MatkulForm
from .models import Matkul
# Create your views here.
def matkul(request):
    if request.method == "POST":
        Matkul.objects.get(id=request.POST['id']).delete()
        return redirect('/daftar_matkul/')
    subjects = Matkul.objects.all()
    context = {'daftar_matkul':subjects}
    return render(request, 'daftar_matkul.html', context)
    

def tambah_matkul(request):
    submit = False
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/tambah/?submit=True')
    else:
        form = MatkulForm
        if 'submit' in request.GET:
            submit = True
    context = {'form': form, 'submit': submit}
    return render(request, 'tambah_matkul.html', context)

def detail_matkul(request, index):
    subject = Matkul.objects.get(pk=index)
    context = {'subject':subject}
    return render(request, 'detail_matkul.html', context)


    
    

stori6/views.py
from django.shortcuts import render, redirect
from .forms import EventForm, ParticipantForm
from .models import Event, Participant

# Create your views here.
def event(request):
    kegiatan = Event.objects.all()
    partisipan = Participant.objects.all()

    if request.method == "POST":
        Participant.objects.get(id=request.POST['id']).delete()
        return redirect('/daftar_event/')

    return render(request, 'daftar_event.html', {'daftar_event':kegiatan, 'partisipan':partisipan})

def tambah_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/daftar_event/')
    else:
        form = EventForm
    context = {'form': form}
    return render(request, 'tambah_event.html', context)

def registrasi(request, index):
    if request.method == 'POST':
        form = ParticipantForm(request.POST)
        if form.is_valid():
            partisipan = Participant(name=form.data['name'], event=Event.objects.get(id=index))
            partisipan.save()
            return redirect('/daftar_event/')
    else:
        form = ParticipantForm()
    context = {'form': form}
    return render(request, 'registrasi.html', context)

homepage/templates/extra.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Karya Mirsa {% endblock %}

{% block content %}
{% include 'navbar.html' %}
        
        <section id="section-a" class="container-fluid d-flex flex-wrap" >
            <p class="quote align-self-end">
                “Art speaks where words are unable to explain“ <br/>
                - Threadless Artist Mathiole
            </p>
        </section>

        <section id="sectionU" class="container-fluid" style="background-color: #FFAD8A;text-align: center;">
        <section id="section-b" class="container-fluid">
            <div class="section-title mx-auto" style="color: beige;"> 
                <br>
                HASIL KARYA
              </div>
                    <button type="button" class="btn align-self-center" data-toggle="modal" data-target="#exampleModal1">
                        <span class="iconify" data-inline="false" data-icon="ant-design:camera-outlined" style="font-size: 200px;"></span>
                    </button>
                      <h4>HASIL KARYA MIRSA: FOTOGRAFI</h4>
        </section>

          <div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="section-title" id="exampleModalLabel" style="padding:0px;"> hasil kamera saya</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
    
                    <div class="modal-body">
                        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img class="d-block w-100" src="{% static '/img/foto1.jpg' %}" alt="First slide">
                                </div>
    
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/IMG_20180331_162241_HDR.jpg' %}" alt="Second slide">
                                </div>
    
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/IMG_20170315_180840.jpg' %}" alt="Third slide">
                                </div>
    
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/IMG_20180331_161740_HDR.jpg' %}" alt="Fourth slide">
                                </div>
                            </div>
    
                            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
    
                            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section id="section-c" class="container-fluid" style="align-items: center;">
            <button type="button" class="btn align-self-center" data-toggle="modal" data-target="#exampleModal2">
                <span class="iconify" data-icon="map:art-gallery" data-inline="false" style="font-size: 200px;"></span>
            </button>
              <h4>HASIL KARYA MIRSA: SENI DIGITAL</h4>
        </section>

        <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="section-title" id="exampleModalLabel2" style="padding:0px;"> Masih belajar hehe</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <div id="carouselExampleControls2" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img class="d-block w-100" src="{% static '/img/digi1.png' %}" alt="First slide">
                                </div>

                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/digi2.png' %}" alt="Second slide">
                                </div>

                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/digi3.png' %}" alt="Third slide">
                                </div>

                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/digi4.png' %}" alt="Fourth slide">
                                </div>
                            </div>

                            <a class="carousel-control-prev" href="#carouselExampleControls2" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>

                            <a class="carousel-control-next" href="#carouselExampleControls2" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section id="section-d" class="container-fluid" style="align-items: center;">
            <button type="button" class="btn align-self-center" data-toggle="modal" data-target="#exampleModal3">
                <span class="iconify" data-icon="emojione-monotone:pencil" data-inline="false" style="font-size: 200px;"></span>
            </button>
              <h4>HASIL KARYA MIRSA: SKETSA PENSIL</h4>
        </section>

        <div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel3" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="section-title" id="exampleModalLabel3" style="padding:0px;"> Baru coba-coba hehe</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <div id="carouselExampleControls3" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img class="d-block w-100" src="{% static '/img/sket1.jpg' %}" alt="First slide">
                                </div>

                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/sket2.jpg' %}" alt="Second slide">
                                </div>

                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/sket3.jpg' %}" alt="Third slide">
                                </div>

                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/sket4.jpg' %}" alt="Fourth slide">
                                </div>

                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{% static '/img/sket5.jpg' %}" alt="Fourth slide">
                                </div>
                            </div>

                            <a class="carousel-control-prev" href="#carouselExampleControls3" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>

                            <a class="carousel-control-next" href="#carouselExampleControls3" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
         
    </section>

    <section class="back">
            <a href="{% url 'homepage:index' %}">
              <div class="d-flex click-2 m-auto">
                  BACK TO HOME
                </div>
              </a>
    </section>

{% endblock %}

homepage/templates/stori3.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mirsa Salsabila {% endblock %}

{% block content %}
{% include 'navbar.html' %}

        <section id="home" class="container-fluid">
            <h1 class="title"> HALLO!! </h1>
            <p class="subtitle"> Jangan Lupa Bahagia Hari Ini! :)</p>
            <a href="#about">
                <img id="triangle" src="{% static 'triangle.jpg' %}" alt="">
            </a>
        </section>

        <section id="about" class="container-fluid d-flex flex-wrap align-content-center ">
            <div class="section-title mx-auto"> 
                TENTANG SAYA
              </div>
            <div class="row align-items-center justify-content-center">
                <div class="col-sm-5 mr-3">
                    <img class="profpic" src="{% static 'mirsa.jpg' %}" alt="Profile Picture" data-aos="flip-left" data-aos-duration="1500">
                    <article class="text-justify">
                        Hai semua! saya adalah seseorang yang senang  bergelut dengan hal berbau ‘seni’ dan seseorang yang memimpikan banyak hal.
                    </article>
                </div>
                
                <div class="col-sm-4 mr-3">
                    <h4> NAMA LENGKAP </h4>
                    <h5> Mirsa Salsabila </h5>
                    <br>
                    <h4> NOMOR MAHASISWA </h4>
                    <h5> 1906350875 </h5>
                    <br>
                    <h4> PERGURUAN TINGGI </h4>
                    <h5> Fakultas Ilmu Komputer, </h5>
                    <h5> Universitas Indonesia </h5>
                    <br>
                    <h4> EMAIL </h4>
                    <h5> mirsa.salsabila@ui.ac.id </h5>
                </div>
            </div>
        </section>

        <section id="pendidikan" class="container-fluid d-flex flex-wrap align-content-center ">
            <div class="section-title mx-auto"> 
                RIWAYAT PENDIDIKAN
              </div>
            <div class="container">
                <div class="row">
                    <div class="col wf">
                        <img class="smp" src="{% static 'smp6.jpg' %}" alt="SMPN 6 Depok" style="width:180px;height:210px;margin-bottom: 15px;">
                        <h4>SMPN 6 Depok</h4>
                        <br>
                        <h5>2013-2016</h5>
                    </div>
                    <div class="col wf">
                        <img class="sma" src="{% static 'sman3.png' %}" alt="SMAN 3 Depok" style="width:180px;height:200px;">
                        <h4>SMAN 3 Depok</h4>
                        <br>
                        <h5>2016-2019</h5>
                    </div>
                    <div class="col wf">
                        <img class="uni" src="{% static 'Makara_UI.png' %}" alt="Universitas Indonesia" style="width:190px;height:200px;">
                        <h4>Fakultas Ilmu Komputer</h4>
                        <h4>Universitas Indonesia</h4>
                        <h5>2019-sekarang</h5>
                    </div>
                </div>
                </div>
            </div>
        </section>

        <section id="kontak" class="container-fluid">
            <div class="section-title mx-auto">
                MARI BERKENALAN!
            </div>
    
            <div class="row">
                <div class="col-sm-3">
                    <a href="https://instagram.com/mirsalsa" target="_blank">
                    <span class="iconify" data-inline="false" data-icon="ant-design:instagram-outlined" style="color: black; font-size: 75px;"></span>
                    </a>
                </div>
                <div class="col-sm-3">
                    <a href="https://www.linkedin.com/in/mirsa-salsabila-4578ba1a0/" target="_blank">
                        <span class="iconify" data-inline="false" data-icon="jam:linkedin-square" style="color: black; font-size: 75px;"></span>
                    </a>
                </div>
                <div class="col-sm-3">
                    <a href="mailto:mirsa.salsabila@ui.ac.id">
                    <span class="iconify" data-inline="false" data-icon="feather:mail" style="color: black; font-size: 75px;"></span>
                    </a>
                </div>
                <div class="col-sm-3">
                    <a href="https://twitter.com/mirsasalsa_" target="_blank">
                        <span class="iconify" data-inline="false" data-icon="brandico:twitter-bird" style="color: black; font-size: 75px;"></span>
                    </a>
                </div>
            </div>                      
          </section> 

          
{% endblock %}

stori1/templates/stori1.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Grandstander:wght@200&family=Poller+One&family=Amatic+SC:wght@700&family=Kalam:wght@700&display=swap" rel="stylesheet">
    </head>
    <body>

        <div class="header">
            <h1>
                My profile
            </h1>
        </div>
        
        <div class="profile">
            <div class="profile1">
            <h3>Nama</h3>
                <p>Mirsa Salsabila</p>

            <h3>NPM</h3>
                <p>1906350875</p>

            <h3>Angkatan</h3>
                <p>2019</p>

            <h3>Kampus</h3>
                <p>Fasilkom, Universitas Indonesia</p>

            <h3>Hobi</h3>
                <ul>
                    <li>Menggambar</li>
                    <li>Menonton Film</li>
                </ul>
            
            
            <h3>Riwayat Pendidikan</h3>
            <table border='1'>
                <tr align="center">
                    <th> <b> Tahun </b> </th>
                    <th> <b> Nama Sekolah </b> </th>
                
                <tr>
                    <td align="center"> 2019 - Sekarang </td>
                    <td> Universitas Indonesia </td> 
                </tr>
                
                <tr>
                    <td align="center"> 2016 - 2019 </td>
                    <td> SMAN 3 Depok </td>
                </tr>
                </tr>
                
                <tr>
                    <td align="center"> 2013 - 2016 </td>
                    <td> SMPN 6 Depok </td>
                </tr>
                
                <tr>
                    <td align="center"> 2007 - 2013 </td>
                    <td> SDN Cilodong 1 </td>
                </tr>
                
                <tr>
                    <td align="center"> 2006 - 2007 </td>
                    <td> TK Dewi Sartika </td>
                </tr>
            </table>
        </div> 

            <div class="profile2">
            <h3>Deskripsi tentang saya</h3>
                <p>Seorang mahasiswi yang sedang mencari minat :)</p>

            <h3>Media Sosial</h3>
                <p>Instagram/Twitter/ID Line = mirsalsa</p>
    

            <h3>Media</h3>
            <img align="center" src="{% static 'mirsa.jpg' %}" width="300" height="300"/>
            </div>
        </div>

    </body>
</html>

stori5/templates/daftar_matkul.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Daftar Matkul {% endblock %}

{% block content %}
{% include 'navbar.html' %}


<section id="about" class="container-fluid d-flex flex-wrap ">
<div>

</div>

<div class="container-fluid"> 
  <div class="section-title"> 
    <h3 >Mata Kuliah-Ku</h3>
  </div>
  <button class="btn btn-primary d-flex m-auto click" style="justify-content: right;"> 
    <a href="{% url 'stori5:tambah_matkul' %}" class="text-white">
      Tambah Mata Kuliah
    </a>
  </button>
  <br>
  {% for i in daftar_matkul %}
    <div class="card w-100">
      <div class="card-body">
        <h5 class="card-title">{{ i.subject }}</h5>
        <p class="card-text">{{ i.deskripsi }}</p>
        <div class="d-flex flex-row">
          <form method="POST" action="{% url 'stori5:matkul' %}">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ i.id }}">
            <button type="submit" value="Submit" class="card-link btn btn-danger">Hapus</button>
          </form>
          <a style="margin-left: 20px;" href="{% url 'stori5:detail_matkul' i.id %}" class="card-link btn btn-outline-primary">Detail</a>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
</section>
{% endblock %}

stori5/templates/detail_matkul.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Detail Matkul {% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id="about" class="container-fluid d-flex flex-wrap align-content-center ">
    <div class="section-title mx-auto"> 
      {{ subject.subject }}
    </div>
    <table class="table table-warning table-bordered table-hover">
        <tbody>
        <tr>
            <td>Dosen</td>
            <td>{{ subject.dosen }}</td>
        </tr>
        <tr>
            <td>SKS</td>
            <td>{{ subject.sks }}</td>
        </tr>
        <tr>
            <td>Semester</td>
            <td>{{ subject.semester }}</td>
        </tr>
        <tr>
            <td>Kelas</td>
            <td>{{ subject.kelas }}</td>
        </tr>
        <tr>
            <td>Deskripsi</td>
            <td>{{ subject.deskripsi }}</td>
        </tr>
    </table>
    <button class="btn btn-primary d-flex m-auto click"> 
        <a href="{% url 'stori5:matkul' %}" class="text-white">
          Kembali ke daftar matkul
        </a>
      </button>

</section>
{% endblock %}

stori5/templates/tambah_matkul.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Tambah Matkul {% endblock %}

{% block content %}
{% include 'navbar.html' %}

    <section class="container">
{% if submit%}
    <div class="section-title mx-auto text-center p-5">
      <p>Mata kuliah yang kamu masukkan berhasil ditambahkan</p>
      <br>
      <button class="btn btn-primary d-flex m-auto click"> 
      <a href="{% url 'stori5:matkul' %}" class="text-white">
        Back to Subject List
      </a>
      </button>
    </div> 

{% else %}
    <div class="section-title mx-auto text-center p-5"> 
      Tambah Mata Kuliah
    </div>

    <form action="" method="post" novalidate>
      {% csrf_token %}
      <table class="table table-danger table-bordered table-hover">
        {{ form.as_table }}
        <tr>
          <td>&nbsp;</td>
          <td><input type="submit" value="Submit" class="btn btn-primary click"></td>
        </tr>
      </table>
    </form>
{% endif %}

</section> 


{% endblock %}

stori6/templates/daftar_event.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Daftar Event {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="about" class="container-fluid d-flex flex-wrap ">
    
    <div class="container-fluid"> 
      <div class="section-title"> 
        <h3 >DAFTAR KEGIATAN</h3>
      </div>
      <button class="btn btn-primary d-flex m-auto click" style="justify-content: right;"> 
        <a href="{% url 'stori6:tambah_event' %}" class="text-white">
          Tambah Event
        </a>
      </button>
      <br>
      {% for i in daftar_event %}
      <div class="card bg-light mb-3" style="max-width: 18rem;">
        <div class="card-header" style="font-size: 20px;">{{i.name}}</div>
        <div class="card-body">
          {% for j in partisipan %}
            {% if j.event == i%}
          <p class="card-title">
            <div class="d-flex flex-row">
                <div>{{ j.name }}</div>
            <form method="POST" action="{% url 'stori6:event' %}">
              {% csrf_token %}
              <input type="hidden" name="id" value="{{j.id}}">
              <button type="submit" value="Submit" class="card-link btn btn-danger">x</button>
          </form>
            </div>
            
          </p>
            {% endif %}
          {% endfor %}
          <a style="margin-left: 20px;" href="{% url 'stori6:registrasi' i.id %}" class="card-link btn btn-outline-primary">Ayo Daftar!!</a>
        </div>
      </div>
        <!-- <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ i.name }}</h5>
            {% for j in partisipan %}
                {% if j.event == i%}  
                    
                    <div class="d-flex flex-row">
                      <p class="card-text">{{ j.name }}</p>
                      <form method="POST" action="{% url 'stori6:event' %}">
                          {% csrf_token %}
                          <input type="hidden" name="id" value="{{j.id}}">
                          <button type="submit" value="Submit" class="card-link btn btn-danger">x</button>
                      </form>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="d-flex flex-row">
                <a style="margin-left: 20px;" href="{% url 'stori6:registrasi' i.id %}" class="card-link btn btn-outline-primary">Ayo Daftar!!</a>
            </div>
        </div> -->
        {% endfor %}
    </div>
    </section>
{% endblock %}

stori6/templates/registrasi.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Daftar Event {% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section class="container">
    <div class="section-title mx-auto text-center p-5"> 
        DAFTARKAN DIRIMU!!
      </div>
  
      <form action="" method="post" novalidate>
        {% csrf_token %}
        <table class="table table-danger table-bordered table-hover">
          {{ form.as_table }}
          <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Submit" class="btn btn-primary click"></td>
          </tr>
        </table>
      </form>
</section>
{% endblock content%}

stori6/templates/tambah_event.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Daftar Event {% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section class="container">
    <div class="section-title mx-auto text-center p-5"> 
        TAMBAH EVENT
      </div>
  
      <form action="" method="post" novalidate>
        {% csrf_token %}
        <table class="table table-danger table-bordered table-hover">
          {{ form.as_table }}
          <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Submit" class="btn btn-primary click"></td>
          </tr>
        </table>
      </form>
</section>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container">
    <a class="navbar-brand" href="#">Mirsalsa</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="col-auto">
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:index' %}#home">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homepage:index' %}#about">Tentang Saya</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}#pendidikan">Pendidikan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:extra' %}">Karya</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}#kontak">Kontak</a>
        </li>
        <li class="nav-item dropdown mx-3">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Etc
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'stori1:home' %}">Story 1 PPW</a>
              <a class="dropdown-item" href="{% url 'stori5:matkul' %}">Daftar Matkul</a>
              <a class="dropdown-item" href="{% url 'stori6:event' %}">Event</a>
            </div>
            
        </li>
      </ul>
    </div>
    </div>
    </div>
</nav>